name: rpg-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - pip=23.1.2
  - pip:
    - flask-socketio==5.3.4
    - python-socketio==5.8.0
    - python-dotenv==1.0.0
    - speechrecognition==3.10.0
    - google-generativeai==0.3.1 